spring.application.name=user-service-docker
spring.datasource.url=jdbc:mysql://110.11.191.24:13306/userdb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul
spring.datasource.username=userapp
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect